name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # deploy to hathora cloud
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm install @hathora/cli -g
      - name: Hathora version
        run: hathora-cloud --version
      - name: Deploy
        run: hathora-cloud deploy --appId app-e2476b33-a573-4d45-9a04-39e80a3a31fd --token ${{ secrets.HATHORA_CLOUD_TOKEN }}
